### ISSUE TITLE
Support textarea reactive value

### ISSUE THREAD

**Issue by jonasstrehle** [unyt-org/uix#166]
see https://discord.com/channels/928247036770390016/1261380437482410035

**Comment by jonasstrehle** [comment]
UIX is supporting both notations:
 
```tsx
const ref = $(0)
<textarea value={ref}/>
```

and

```tsx
const ref = $(0)
<textarea>{ref}</textarea>
```

The first is necessary for handling unidirectional data binding (`value:out` and `value:in`), the latter is the "How it should be used in 99% of the cases"-solution - similar as it would be achieved in HTML. Note that the value attribute for textarea is against HTML Spec, this is why for bidirectional binding the second example should be the recommended way in docs.
@unyt-org/admin @benStre @asbng

**Comment by benStre** [comment]
nice!
