### ISSUE TITLE
CLI stalls on JSX Parser Syntax Error

### ISSUE THREAD

**Issue by asbng** [unyt-org/uix#37]
Execution of the `uix` command in a freshly setup UIX Base Project, with a syntax-breaking change to `common/page.tsx` results in a stalled situation where the user has to press the Return key to see the JSX Parser error.

![image](https://github.com/unyt-org/uix/assets/138817889/175d4604-b579-4d65-82a8-fc93711c940b)
<sup>Invalid syntax in page.tsx</sup>

![image](https://github.com/unyt-org/uix/assets/138817889/42f90778-fe8d-4688-a11e-324c2dc71150)
<sup>Return key is required before the CLI proceeds to show the error and exit</sup>

**Comment by benStre** [comment]
This is fixed now, but with the tradeoff that we need to disable the DATEX CLI that reads from stdin and seems to block error messages until the read is finished (by pressing enter).

https://deno.land/x/input@2.0.3/index.ts

Probably a deno bug/missing feature
