### ISSUE TITLE
Introduction of a "uix init" command

### ISSUE THREAD

**Issue by asbng** [unyt-org/uix#38]
Instead of having to clone the UIX Base Project Repository manually, a `uix init` command could be introduced that clones the repository and performs certain adaptions on the basis of user input.

These adaptions could include:
- frontend, backend or hybrid rendering setup
- mostly empty, mildly preconditioned or highly populated example base files
- plugins etc.

**Comment by benStre** [comment]
`uix --init` is already implemented, but custom initial configuration options are not yet supported.

Also, the --init command does not seem to work for all operating systems/setups.

**Comment by jonasstrehle** [comment]
UIX does now support the `--template` arg.

Syntax: `uix --init myProject --template deployment`
