### ISSUE TITLE
[Docs] Mention Deno Extension

### ISSUE THREAD

**Issue by asbng** [unyt-org/uix#42]
The VSCode section in the Getting Started manual should briefly mention the requirement of the Deno extension as otherwise, linting might not work at all despite VSCode recognizing the .ts and .tsx files correctly and thus tricking users into thinking the base requirements are already there.

**Comment by benStre** [comment]
It's already mentioned in the note (https://docs.unyt.org/manual/uix/getting-started#creating-a-new-uix-project) - or am I missing something?

**Comment by asbng** [comment]
Sorry, you're right, nevermind.
