### ISSUE TITLE
Tailwindcss support

### ISSUE THREAD

**Issue by helmuth99** [unyt-org/uix#51]
Ich will Tailwindcss und uix nutzen. Ich hab schon im Discord gefragt und wurde gebeten ein Issue zu erstellen. Anscheinend müsste man einige dinge erledigen sowie ein custom UIX theme erstellen. Kann hier weiter erläutert werden, wie ich tailwind und uix zusammen nutzen kann.

**Comment by benStre** [comment]
Es gibt jetzt ein "tailwindcss" theme das mit UIX mitgeliefert wird ([v.0.1.20](https://github.com/unyt-org/uix/releases/tag/v0.1.20)).

Kann wie ein ganz normales UIX theme verwendet werden, also z.b in einer `common/theme.ts` datei:
```ts
import { UIX } from "uix";
import { tailwindcss } from "uix/themes/tailwindcss.ts"
UIX.Theme.useTheme(tailwindcss)
```

und die datei dann im backend + frontend entrypoint importieren.

Es wird auch automatisch eine `tailwind.config.js` und eine `tailwind.css` datei im project root angelegt.
Tailwind sollte auch automatisch installiert werden, npm wird aber benötigt. Unter windows kann ich nicht garantieren dass es funktioniert.

**Comment by ren0x** [comment]
Cool, danke! Gleich als einen weiteren Vorschlag vielleicht [Bootstrap](https://getbootstrap.com/)? Noch binde ich es über ein custom theme ein, wie in den Docs vorgeschlagen:

```js
// Bootstrap theme
UIX.Theme.setMode('light');
UIX.Theme.useThemes("uix-light-plain")

UIX.Theme.registerTheme({
  name: 'bootstrap-light-theme',
  mode: 'light', 
  stylesheets: [
    'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css'
  ],
  onActivate() {
    console.log("bla");
  }
});

UIX.Theme.useThemes("bootstrap-light-theme");
```

Semantisch scheint mir das aber suboptimal, weil es nicht wirklich "mein custom theme" ist. Wäre cool, wenn man beides einbinden könnte! :)
