### ISSUE TITLE
Component imports fail if folder did not exist at UIX process start

### ISSUE THREAD

**Issue by nwLSteam** [unyt-org/uix#74]
## Prerequisites

I have the following code in `frontend/components/TestComponent.tsx`
```tsx
import { Component } from "uix/components/Component.ts";

@template(() => <div>Hello World!</div>)
export default class TestComponent extends Component { }
```
I then create a file `frontend/routes/example.tsx`:
```tsx
import TestComponent from "../components/TestComponent.tsx";

function Example() {
    return <div>
        <TestComponent />
    </div>
}

export default Example;
```
This works, and the component displays.

## Expected
I now move the file:
- `frontend/components/TestComponent.tsx` 
  -> `frontend/foobar/TestComponent.tsx`

and update the import:

- `import TestComponent from "../components/TestComponent.tsx";` 
  ->`import TestComponent from "../foobar/TestComponent.tsx";`

and the component should still display.

## Actual

The component does **not** display.
- I get no warning in the backend console.
- The browser console says:
  ```
  Loading failed for the module with source “http://localhost:58672/@uix/src/frontend/foobar/TestComponent.tsx”. example:55:39
  Loading module from “http://localhost:58672/@uix/src/frontend/foobar/TestComponent.tsx” was blocked because of a disallowed MIME type (“text/plain”). example
  Uncaught (in promise) TypeError: error loading dynamically imported module: http://localhost:58672/@uix/src/frontend/routes/example.tsx
  Uncaught TypeError: error loading dynamically imported module: http://localhost:58672/@uix/src/frontend/routes/example.tsx
  ```
  and the link `http://localhost:58672/@uix/src/frontend/foobar/TestComponent.tsx` leads to a page saying `Not Found`.

## Notes

This also happens if the file is in a subfolder of `components`, e.g. `frontend/components/foobar`.

**Comment by benStre** [comment]
@nwLSteam Just to clarify - this error still occurs after restarting UIX?
Can you provide your current UIX version and the command line arguments you used?

**Comment by nwLSteam** [comment]
```
UIX v0.1.42 (https://cdn.unyt.org/uix/)

DATEX Core:  v0.0.46 (https://cdn.unyt.org/datex-core-js-legacy/)
Deno:        1.39.4
TypeScript:  5.3.3
V8:          12.0.267.8
```
I run UIX with `uix -wblr`. 

Restarting UIX fixes the issue. However, after restarting UIX, renaming the `foobar` dir and changing the import to point to the new dir makes it break again. I have adjusted the issue title accordingly.
