### ISSUE TITLE
SCSS imports fail during UIX startup

### ISSUE THREAD

**Issue by nwLSteam** [unyt-org/uix#78]
## Prerequisites
I have a `/frontend/entrypoint.scss`:
```scss
@use 'styles/global';
```
and a  `/frontend/styles/_global.scss`:
```scss
body {
    background-color: red;
}
```
## Expected
I start the `uix` process and my CSS transpiles and is used for the website.

## Actual
On the initial `uix` start, I get an error:
```
 transpiler  SCSS error (/mnt/e/Libraries/Programming/JS/project-name/frontend/entrypoint.scss): Error: Can't find stylesheet to import.
  ╷
1 │ @use 'styles/global';
  │                     ^
  ╵
.//tmp/transpiler_cache_1dbd724b/frontend.transpiled.web/entrypoint.scss:1:21
```
and the CSS is *not* used on the website. 

**However**, updating the `/frontend/entrypoint.scss` file (for example by adding a space and saving) re-runs the transpiler, and *then* the imports work, and the CSS is shown correctly.

## Environment
**OS**: Ubuntu 20.04.6 LTS on WSL
**Command:** `uix -wblr`
**Version:**
```
UIX v0.1.42 (https://cdn.unyt.org/uix/)

DATEX Core:  v0.0.46 (https://cdn.unyt.org/datex-core-js-legacy/)
Deno:        1.39.4
TypeScript:  5.3.3
V8:          12.0.267.8
```

**Comment by benStre** [comment]
Fixed in https://github.com/unyt-org/uix/pull/79

**Comment by nwLSteam** [comment]
This is not fixed.
```
 transpiler  SCSS error (/mnt/e/Libraries/Programming/JS/project-name/frontend/entrypoint.scss): Error: Can't find stylesheet to import.
  ╷
1 │ @use 'styles/global';
  │                     ^
  ╵
.//tmp/transpiler_cache_2bf52e8a/frontend.transpiled.web/entrypoint.scss:1:21


Connected to the Supranet via @+unyt1 (websocket to relay1.unyt.cc) 

APP           Project Name
ENDPOINT      @@[censored]/0002
APP URL       https://[censored].unyt.app     

STAGE         dev

UIX VERSION   0.1.43
DATEX VERSION 0.0.46

© 2024 unyt.org

 UIX Server  frontend available on http://localhost:1255
 UIX Frontend  hot reloading enabled
```

**Comment by benStre** [comment]
> This is not fixed.
> 
> ```
>  transpiler  SCSS error (/mnt/e/Libraries/Programming/JS/project-name/frontend/entrypoint.scss): Error: Can't find stylesheet to import.
>   ╷
> 1 │ @use 'styles/global';
>   │                     ^
>   ╵
> .//tmp/transpiler_cache_2bf52e8a/frontend.transpiled.web/entrypoint.scss:1:21
> 
> 
> Connected to the Supranet via @+unyt1 (websocket to relay1.unyt.cc) 
> 
> APP           Project Name
> ENDPOINT      @@[censored]/0002
> APP URL       https://[censored].unyt.app     
> 
> STAGE         dev
> 
> UIX VERSION   0.1.43
> DATEX VERSION 0.0.46
> 
> © 2024 unyt.org
> 
>  UIX Server  frontend available on http://localhost:1255
>  UIX Frontend  hot reloading enabled
> ```

We could not reproduce this with the current UIX version.
Can you provide us with your scss/css file paths and contents?
Can you also provide the directory contents of your current transpile directory (e.g `/tmp/transpiler_cache_1dbd724b/frontend.transpiled.web/styles/`)

**Comment by nwLSteam** [comment]
While creating an MVE, UIX updated to `0.1.45`, after which the issue was fixed. I have no way of discovering whether your initial fix worked or if a subsequent one happened, but I can close this ticket now since the issue is resolved.
